"""add users and tenancy user_id

Revision ID: e0c9b9255b45
Revises: 4fdb2a49229c
Create Date: 2026-07-19 01:15:42.910415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c9b9255b45'
down_revision: Union[str, None] = '4fdb2a49229c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_broker_connections_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_broker_connections_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_portfolios_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_watchlist_ticker'))
        batch_op.create_index(batch_op.f('ix_watchlist_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_watchlist_user_ticker', ['user_id', 'ticker'])
        batch_op.create_foreign_key('fk_watchlist_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_constraint('fk_watchlist_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_watchlist_user_ticker', type_='unique')
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_ticker'))
        batch_op.create_index(batch_op.f('ix_watchlist_ticker'), ['ticker'], unique=1)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_portfolios_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_broker_connections_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_broker_connections_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
