"""initial schema

Revision ID: 4fdb2a49229c
Revises: 
Create Date: 2026-07-19 00:33:22.455164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdb2a49229c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_benchmark_history_date')
    )
    with op.batch_alter_table('benchmark_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_history_ticker'), ['ticker'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_filename', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_id'), ['id'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_ticker'), ['ticker'], unique=True)

    op.create_table('broker_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('connection_state', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broker_connections_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('price_status', sa.String(length=30), nullable=True),
    sa.Column('price_source', sa.String(length=40), nullable=True),
    sa.Column('price_timestamp', sa.DateTime(), nullable=True),
    sa.Column('price_failure_reason', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('purchase_date', sa.String(length=20), nullable=True),
    sa.Column('normalized_ticker', sa.String(length=30), nullable=True),
    sa.Column('sector_status', sa.String(length=20), nullable=True),
    sa.Column('name_status', sa.String(length=20), nullable=True),
    sa.Column('enrichment_reason', sa.Text(), nullable=True),
    sa.Column('enrichment_status', sa.String(length=20), nullable=True),
    sa.Column('fundamentals_status', sa.String(length=20), nullable=True),
    sa.Column('peers_status', sa.String(length=20), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_ticker'), ['ticker'], unique=False)

    op.create_table('portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_portfolio_history_date')
    )
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_history_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_pnl_pct', sa.Float(), nullable=True),
    sa.Column('num_holdings', sa.Integer(), nullable=True),
    sa.Column('top_sector', sa.String(length=100), nullable=True),
    sa.Column('sector_weights_json', sa.Text(), nullable=True),
    sa.Column('risk_metrics_json', sa.Text(), nullable=True),
    sa.Column('top_holdings_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('snapshot_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_holdings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshot_holdings_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_holdings_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_snapshot_holdings_id'))

    op.drop_table('snapshot_holdings')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_captured_at'))

    op.drop_table('snapshots')
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_history_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_history_id'))

    op.drop_table('portfolio_history')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_ticker'))
        batch_op.drop_index(batch_op.f('ix_holdings_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_connections_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_broker_connections_id'))

    op.drop_table('broker_connections')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_ticker'))
        batch_op.drop_index(batch_op.f('ix_watchlist_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('benchmark_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_history_ticker'))
        batch_op.drop_index(batch_op.f('ix_benchmark_history_id'))

    op.drop_table('benchmark_history')
    # ### end Alembic commands ###
